### ISSUE TITLE
update queries for SUA

### ISSUE THREAD

**Issue by critzo** [m-lab/data-support#6]
Data integration from SUA uses these [queries](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb#L73-L127). Update them to use new unified views, or add filters used by our unified views.

**Comment by critzo** [comment]
@mattmathis Could you confirm the equivalence of these two queries before I provide them to SUA? My primary concern is that the queries filter for valid tests since they do not use the unified views.

* [original upload query](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb#L73-L97) --- [replacement upload query](https://github.com/m-lab/data-support/blob/issue6/support/issue6/upload.sql)
* [original download query](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb#L103-L127) --- [replacement download query](https://github.com/m-lab/data-support/blob/issue6/support/issue6/upload.sql)

**Comment by mattmathis** [comment]
Test with my alpha views: mlab-sandbox.mm_unified_testing.ndt_unified_ndt5_{up,down}loads.
I can easily add or rearrange stuff in _raw as you need it, and over the longer term move fully supported features to proper locations in the main part of the view.

These are on-deck to be checked in as production views.  They will appear at measurement-lab.library.   I am currently working on testing infrasture to validate them, going forward.

There will be an interesting discussion about (non)support of _raw, but I have a plan. 

Please let me know ASAP if you can't access my alpha views.

**Comment by critzo** [comment]
Thanks @mattmathis Here is a sample download query using your sandbox view.
I've added ``` 'missing' AS ... ``` to indicate fields needed but not present in the schema, and comment(s) following these to indicate where I what field was used previously or is desired.

```
#standardSQL
    SELECT 
      'missing' AS test_id,  #ParseInfo.TaskFileName
      a.TestTime AS UTC_date_time,
      client.IP AS client_ip,
      Client.Geo.latitude AS client_latitude,
      Client.Geo.longitude AS client_longitude,
      Client.Geo.country_code AS country_code,
      Client.Geo.region AS region,
      Client.Geo.city AS city,
      Client.Geo.postal_code AS postal_code,
      a.MeanThroughputMbps AS downloadThroughput,
      NULL AS uploadThroughput,
      'missing' AS duration,
      'missing' AS HCThruOctetsRecv
      #TIMESTAMP_DIFF(result.S2C.EndTime, result.S2C.StartTime, MICROSECOND) AS duration,
      #FinalSnapshot.TCPInfo.BytesReceived AS HCThruOctetsRecv
    FROM `mlab-sandbox.mm_unified_testing.unified_downloads`
    WHERE
      test_date BETWEEN '2020-01-01' AND '2020-01-31'
      AND Client.Geo.country_code = 'US'
      AND Client.Geo.region = 'OR'
    ORDER BY UTC_date_time ASC
```

**Comment by critzo** [comment]
I've provided the following queries to SUA in a [PR](https://github.com/Hack4Eugene/SpeedUpAmerica/pull/251) after confirming they are efficient and return the expected fields. Joining on UUID in both `ndt5` and `tcpinfo` was needed:

```
#standardSQL
    SELECT 
      tcpinfo.ParseInfo.TaskFileName AS test_id,  
      a.TestTime AS UTC_date_time,
      ndt.client.IP AS client_ip,
      ndt.Client.Geo.latitude AS client_latitude,
      ndt.Client.Geo.longitude AS client_longitude,
      ndt.Client.Geo.country_code AS country_code,
      ndt.Client.Geo.region AS region,
      ndt.Client.Geo.city AS city,
      ndt.Client.Geo.postal_code AS postal_code,
      a.MeanThroughputMbps AS downloadThroughput,
      NULL AS uploadThroughput,
      TIMESTAMP_DIFF(ndt5.result.S2C.EndTime, ndt5.result.S2C.StartTime, MICROSECOND) AS duration,
      FinalSnapshot.TCPInfo.BytesReceived AS HCThruOctetsRecv
    FROM `measurement-lab.ndt.unified_downloads` ndt,
         `measurement-lab.ndt.ndt5` ndt5,
         `measurement-lab.ndt.tcpinfo` tcpinfo
    WHERE
      a.UUID = tcpinfo.UUID
      AND a.UUID = ndt5.result.S2C.UUID
      AND test_date BETWEEN '#{start_date}' AND '#{end_date}'
      AND ndt.Client.Geo.country_code = '#{country_code}'
      AND ndt.Client.Geo.region = '#{region}'
    ORDER BY UTC_date_time ASC
```

```
#standardSQL
    SELECT 
      tcpinfo.ParseInfo.TaskFileName AS test_id,  
      a.TestTime AS UTC_date_time,
      ndt.client.IP AS client_ip,
      ndt.Client.Geo.latitude AS client_latitude,
      ndt.Client.Geo.longitude AS client_longitude,
      ndt.Client.Geo.country_code AS country_code,
      ndt.Client.Geo.region AS region,
      ndt.Client.Geo.city AS city,
      ndt.Client.Geo.postal_code AS postal_code,
      a.MeanThroughputMbps AS uploadThroughput,
      NULL AS downloadThroughput,
      TIMESTAMP_DIFF(ndt5.result.S2C.EndTime, ndt5.result.S2C.StartTime, MICROSECOND) AS duration,
      FinalSnapshot.TCPInfo.BytesReceived AS HCThruOctetsRecv
    FROM `measurement-lab.ndt.unified_uploads` ndt,
         `measurement-lab.ndt.ndt5` ndt5,
         `measurement-lab.ndt.tcpinfo` tcpinfo
    WHERE
      a.UUID = tcpinfo.UUID
      AND a.UUID = ndt5.result.S2C.UUID
      AND test_date BETWEEN '#{start_date}' AND '#{end_date}'
      AND ndt.Client.Geo.country_code = '#{country_code}'
      AND ndt.Client.Geo.region = '#{region}'
    ORDER BY UTC_date_time ASC
```
